[CI]: Check Darwin from ci-hook

diff --git a/.ci/run b/.ci/run
--- a/.ci/run
+++ b/.ci/run
@@ -7,8 +7,15 @@ set -e
 
 if [ "`id -un`" = "root" ]; then
     if [ -d ".ci" ]; then
-	groupadd ci
-	useradd -g ci ci
+	if [ "`uname`" = "Darwin" ]; then
+	    if ! [ -f /Users/ci ]; then
+		echo "Error: User ci not found."
+		exit 1
+	    fi
+	else
+	    groupadd ci
+	    useradd -g ci ci
+	fi
 	chown -R ci:ci .
 	su  -c ./.ci/build_and_test_world ci
     else
